package com.team30.syntaxrunner;

import java.util.ArrayList;
import java.util.List;

/**
 * Validates that for every sub-question in a QuestionBank, concatenating
 * the FIRST option of every token position equals [Answer-x] after
 * whitespace normalisation. Mismatches are printed with full context.
 *
 * Generated by GenAI. -- Etienne Gu
 */
public class BankValidator {

    /**
     * @param label human-readable bank name, used in log output
     * @param bank  the QuestionBank to validate
     */
    public static void validate(String label, QuestionBank bank) {
        System.out.println("===== Validating " + label + " =====");
        int problems = 0;
        int total = bank.size();

        for (int id = 0; id < total; id++) {
            String[][] raw = bank.getRawQuestion(id);
            if (raw == null) continue;

            Question q = new Question(raw);
            for (SubQuestion sq : q.getAllSubQuestions()) {
                StringBuilder firstChain = new StringBuilder();
                List<String> tokens = sq.getTokens();
                List<String> missing = new ArrayList<>();

                for (int t = 0; t < tokens.size(); t++) {
                    List<String> opts = sq.getTokenOptions(t);
                    if (opts == null || opts.isEmpty()) {
                        missing.add(String.valueOf(t + 1));
                        firstChain.append(tokens.get(t));
                    } else {
                        firstChain.append(opts.get(0));
                    }
                }

                String userNorm     = firstChain.toString().replaceAll("\\s+", "");
                String acceptedNorm = sq.getAnswers().isEmpty()
                        ? ""
                        : sq.getAnswers().get(0).replaceAll("\\s+", "");

                if (!userNorm.equals(acceptedNorm)) {
                    problems++;
                    System.out.println("MISMATCH  id=" + id +
                            "  Question-" + sq.getQuestionNumber());
                    System.out.println("   Question-x : " + firstChain);
                    System.out.println("   accepted    : " +
                            (sq.getAnswers().isEmpty() ? "<none>" : sq.getAnswers().get(0)));
                    if (!missing.isEmpty()) {
                        System.out.println("   missing Options-" +
                                sq.getQuestionNumber() + "-" + missing);
                    }
                }
            }
        }
        System.out.println("Total mismatches in " + label + ": " + problems);
        System.out.println();
    }
}
