import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * A "fake player" used to validate the {@link Judger} without a real UI.
 *
 * <p>For each token position in each sub-question, the TestCollector
 * picks one option string. Two modes are supported:
 * <ul>
 *   <li>{@link Mode#RANDOM} — pick a uniformly random option. Most runs
 *       will be judged false, occasionally true if all picks happen to
 *       form a valid answer.</li>
 *   <li>{@link Mode#ALWAYS_CORRECT} — pick the first option, which by
 *       our QuestionBank convention is the correct one. Every run
 *       should be judged true; useful as a positive regression test.</li>
 * </ul>
 *
 * <p>If a token position has no options, the original clean token is
 * used instead, so concatenation still produces a sensible string.
 *
 * Generated by GenAI. -- Etienne Gu
 */
public class TestCollector
{

    /** Behaviour mode of the fake player. */
    public enum Mode {
        /** Pick a random option for every token position. */
        RANDOM,
        /** Always pick the first option (the correct one by convention). */
        ALWAYS_CORRECT
    }

    private final Mode mode;
    private final Random random;

    /** Creates a TestCollector in {@link Mode#RANDOM} with a fresh RNG. */
    public TestCollector()
    {
        this(Mode.RANDOM, new Random());
    }

    /** Creates a TestCollector in the given mode with a fresh RNG. */
    public TestCollector(Mode mode)
    {
        this(mode, new Random());
    }

    /**
     * Creates a TestCollector with explicit mode and RNG. A seeded RNG
     * is handy for reproducible test runs.
     *
     * @param mode   the behaviour mode
     * @param random the random source
     */
    public TestCollector(Mode mode, Random random)
    {
        this.mode = mode;
        this.random = random;
    }

    /**
     * Walks every sub-question of the given {@link Question} and picks
     * one option per token position according to the current mode.
     *
     * @param question the parsed question
     * @return map of {@code subQuestionNumber -> ordered list of picked tokens}
     */
    public Map<Integer, List<String>> collectAnswers(Question question)
    {
        Map<Integer, List<String>> result = new HashMap<>();
        if (question == null) return result;

        for (SubQuestion sq : question.getAllSubQuestions())
        {
            result.put(sq.getQuestionNumber(), pickForSubQuestion(sq));
        }
        return result;
    }

    /**
     * Picks one option per token position for a single sub-question.
     * Returned strings are taken from the clean view, so the assembled
     * answer matches what the Judger expects.
     *
     * @param sq the sub-question
     * @return the ordered list of picked tokens
     */
    private List<String> pickForSubQuestion(SubQuestion sq)
    {
        List<String> picks = new ArrayList<>();
        List<String> tokens = sq.getTokens();

        for (int i = 0; i < tokens.size(); i++)
        {
            List<String> options = sq.getTokenOptions(i);
            if (options == null || options.isEmpty())
            {
                // Fallback: no options for this token, just keep the original token.
                picks.add(tokens.get(i));
                continue;
            }
            picks.add(pickOne(options));
        }
        return picks;
    }

    /**
     * Selects one option according to the current mode.
     *
     * @param options the option list (guaranteed non-empty by caller)
     * @return the picked option string
     */
    private String pickOne(List<String> options)
    {
        switch (mode)
        {
            case ALWAYS_CORRECT:
                return options.get(0);
            case RANDOM:
            default:
                return options.get(random.nextInt(options.size()));
        }
    }

    /** Returns the current mode (handy for logs / assertions). */
    public Mode getMode()
    {
        return mode;
    }
}